@host = http://127.0.0.1:22222
@project = demo1
@verify = test1
@key = VLYOURLICENSEKEY
@hwid = test-hwid-01

### JSON verify
POST {{host}}/api/v1/{{project}}/{{verify}}
Content-Type: application/json

{
  "key": "{{key}}",
  "hwid": "{{hwid}}"
}

### Form verify
POST {{host}}/api/v1/{{project}}/{{verify}}
Content-Type: application/x-www-form-urlencoded

key={{key}}&hwid={{hwid}}
